---
# tasks file for hostname
- name: update the hostname - hostname module
  hostname:
    name: "{{ inventory_hostname }}"

- name: update the hostname - /etc/hostname file
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: update the hostname - /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
